import Link from "next/link";
import { applicationAccessReviews, signInAudienceLabel, type RelationshipEdge, type TenantSnapshot } from "@entra-explorer/domain";

export function ApplicationAccess({ snapshot, query, selectedId }: { snapshot: TenantSnapshot; query: string; selectedId?: string }) {
  const reviews = applicationAccessReviews(snapshot);
  const matches = reviews.filter(({ identity }) => [identity.label, identity.id, identity.appId, identity.publisher, identity.applicationProfile?.homeTenantId, identity.applicationProfile?.verifiedPublisherName].some(value => value?.toLowerCase().includes(query.toLowerCase())));
  const selected = selectedId ? matches.find(r => r.identity.id === selectedId) : matches[0];
  const hiddenSelection = Boolean(selectedId && !selected && reviews.some(review => review.identity.id === selectedId));
  const nodes = new Map(snapshot.nodes.map(n => [n.id, n]));
  const profile = selected?.identity.applicationProfile;
  const knownBoolean = (value: boolean | null | undefined, yes: string, no: string) => value === true ? yes : value === false ? no : "Unknown — not recorded";
  const evidence = (edge: RelationshipEdge) => <><Link href={`/map?edge=${encodeURIComponent(edge.id)}`}>Inspect relationship</Link><details><summary>Source evidence</summary><p>{edge.type} · {edge.evidence.completeness}</p><code>{edge.sourceId} → {edge.targetId}</code><code>{edge.evidence.sourceEndpoint}</code><p>Source records: {edge.evidence.sourceRecordIds.join(", ")}</p></details></>;
  return <>
    <form key={query} className="investigation-search" role="search" aria-label="Filter application access"><input type="hidden" name="view" value="applications" /><label htmlFor="application-query">Filter application names, IDs or publishers</label><input id="application-query" name="q" defaultValue={query} maxLength={200} /><button className="button button-secondary" type="submit">Filter</button></form>
    {selectedId && !selected ? <p role="status" className="notice-banner">{hiddenSelection ? <>The requested application identity is hidden by the current filter. <Link href={`/investigations?view=applications&identity=${encodeURIComponent(selectedId)}#application-access-detail`}>Clear the filter and inspect the requested application</Link>.</> : "The requested application identity is not in this snapshot. Choose a recorded identity from the list below; missing collection does not establish that the application was deleted."}</p> : null}
    <section id="application-identities" className="panel investigation-card" tabIndex={-1}><h2>Application access review</h2><p>Inspect tenant identities, their sign-in configuration, and direct incoming assignments and consent. These settings describe configured access; they do not establish effective access or permission use.</p><p>{matches.length} matching identities.{matches.length > 50 ? " Showing the first 50; refine the filter to find another identity." : ""}</p>
      <div className="table-scroll"><table><thead><tr><th>Tenant identity</th><th>Sign-in audience</th><th>Account state</th><th>Assignment required</th></tr></thead><tbody>{matches.slice(0, 50).map(({ identity }) => <tr key={identity.id}><td><Link aria-current={selected?.identity.id === identity.id ? "true" : undefined} href={`/investigations?view=applications&q=${encodeURIComponent(query)}&identity=${encodeURIComponent(identity.id)}#application-access-detail`}>{identity.label}</Link><br /><code>{identity.id}</code></td><td>{signInAudienceLabel(identity.applicationProfile?.signInAudience)}</td><td>{knownBoolean(identity.applicationProfile?.accountEnabled, "Enabled", "Disabled")}</td><td>{knownBoolean(identity.applicationProfile?.assignmentRequired, "Required", "Not required")}</td></tr>)}</tbody></table></div>{!matches.length ? <p>No application identities match this filter.</p> : null}
    </section>
    {selected ? <section id="application-access-detail" className="panel investigation-card" aria-label="Selected application access" tabIndex={-1}><Link href="#application-identities">Back to application identities</Link><h2>{selected.identity.label}</h2><p>{selected.identity.kind === "managedIdentity" ? "Managed identity" : "Enterprise application (service principal)"}</p>
      <dl><dt>Object ID in this tenant</dt><dd><code>{selected.identity.id}</code></dd><dt>Application (client) ID</dt><dd><code>{selected.identity.appId ?? "Unknown"}</code></dd><dt>Home tenant ID</dt><dd><code>{profile?.homeTenantId ?? "Unknown — not recorded"}</code></dd><dt>Local app registration</dt><dd>{selected.registration ? <>{selected.registration.label} · <code>{selected.registration.id}</code></> : "No matching registration collected. This does not establish external ownership."}</dd><dt>Publisher</dt><dd>{selected.identity.publisher ?? "Unknown — not recorded"}</dd><dt>Verified publisher record</dt><dd>{profile?.verifiedPublisherId ? <>{profile.verifiedPublisherName ?? "Name unavailable"} · <code>{profile.verifiedPublisherId}</code></> : "No verified publisher ID recorded; check source coverage."}</dd><dt>Preferred single sign-on mode</dt><dd>{profile?.preferredSsoMode ?? "Unknown — not recorded"}</dd><dt>Inventory source</dt><dd><code>{selected.identity.sourceEndpoint ?? "Not recorded in this snapshot"}</code></dd></dl>
      <p>A publisher record is identity metadata, not an assessment of application safety. “Assignment not required” does not mean everyone has effective access. Existing sessions, consent, group membership, application authorization and policy evaluation are outside this view.</p>
      <h3>Direct incoming access</h3><p>{selected.incoming.length} configured relationships. App-role assignments: {selected.assignmentsCollected ? "read completed" : "incomplete or unknown"}. Delegated consent: {selected.consentCollected ? "read completed" : "incomplete or unknown"}.</p>
      <div className="table-scroll"><table><thead><tr><th>Principal</th><th>Configured relationship</th><th>Permissions and audience</th><th>Evidence</th></tr></thead><tbody>{selected.incoming.slice(0, 100).map(edge => <tr key={edge.id}><td>{nodes.get(edge.sourceId)?.label ?? "Details unavailable"}<br /><small>{nodes.get(edge.sourceId)?.kind ?? "Unknown type"}</small><br /><code>{edge.sourceId}</code></td><td>{edge.plainLabel}</td><td>{edge.permissions.join(", ") || "No permission names recorded"}{edge.type === "CAN_CALL_DELEGATED" ? <p>{edge.consent?.audience === "all-users" ? "All users" : edge.consent?.audience === "single-user" ? "One user" : "Unknown consent audience"}{edge.consent?.principalId ? <> · <code>{edge.consent.principalId}</code></> : null}</p> : null}</td><td>{evidence(edge)}</td></tr>)}</tbody></table></div>{selected.incoming.length > 100 ? <p>Showing the first 100 incoming relationships. Open the map to explore the complete recorded inventory.</p> : null}{!selected.incoming.length ? <p>No incoming access relationships recorded. Missing collection cannot establish absence.</p> : null}
      <h3>Accountable owners</h3><p>Owner read: {selected.ownersCollected ? "completed" : "incomplete or unknown"}. Owners of the registration and tenant identity are separate assignments.</p><ul>{selected.owners.map(edge => <li key={edge.id}>{nodes.get(edge.sourceId)?.label ?? edge.sourceId} · {evidence(edge)}</li>)}</ul>{!selected.owners.length ? <p>No tenant-identity owners recorded.</p> : null}
      <h3>Observed user sign-ins</h3><p>{selected.observations.length} successful sign-in records targeting this identity. This count does not prove any configured permission was exercised. Missing activity does not establish inactivity; workload sign-ins are not covered. Up to 20 recent records are shown.</p><ul>{selected.observations.slice().sort((a, b) => b.evidence.observed!.lastSeenAt.localeCompare(a.evidence.observed!.lastSeenAt)).slice(0, 20).map(edge => <li key={edge.id}>{nodes.get(edge.sourceId)?.label ?? edge.sourceId} · {edge.evidence.observed!.lastSeenAt} · {evidence(edge)}</li>)}</ul>
    </section> : null}
  </>;
}
